// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

void ui_Garden_screen_init(void)
{
    ui_Garden = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Garden, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Garden);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 120);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LLastWateringG = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LLastWateringG, 160);
    lv_obj_set_height(ui_LLastWateringG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LLastWateringG, -120);
    lv_obj_set_y(ui_LLastWateringG, -120);
    lv_obj_set_align(ui_LLastWateringG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LLastWateringG, "Ostatnie podlewanie:");

    // to do
    // ui_LRainFall = lv_label_create(ui_Garden);
    // lv_obj_set_width(ui_LRainFall, 160);
    // lv_obj_set_height(ui_LRainFall, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_LRainFall, -120);
    // lv_obj_set_y(ui_LRainFall, -60);
    // lv_obj_set_align(ui_LRainFall, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_LRainFall, "Suma opadow:");

    ui_LLastRain = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LLastRain, 160);
    lv_obj_set_height(ui_LLastRain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LLastRain, -120);
    lv_obj_set_y(ui_LLastRain, -90);
    lv_obj_set_align(ui_LLastRain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LLastRain, "Ostatni deszcz:");

    ui_LGardenAut = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LGardenAut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LGardenAut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LGardenAut, 80);
    lv_obj_set_y(ui_LGardenAut, 50);
    lv_obj_set_align(ui_LGardenAut, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LGardenAut, "Tryb automatyczny");

    ui_Label8 = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 120);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Powrot");

    ui_GardenAut = lv_switch_create(ui_Garden);
    lv_obj_set_width(ui_GardenAut, 50);
    lv_obj_set_height(ui_GardenAut, 25);
    lv_obj_set_x(ui_GardenAut, 190);
    lv_obj_set_y(ui_GardenAut, 50);
    lv_obj_set_align(ui_GardenAut, LV_ALIGN_CENTER);


    ui_LcmdG = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LcmdG, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LcmdG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LcmdG, -150);
    lv_obj_set_y(ui_LcmdG, 50);
    lv_obj_set_align(ui_LcmdG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LcmdG, "Podlej rosliny:");

    ui_cmdG = lv_switch_create(ui_Garden);
    lv_obj_set_width(ui_cmdG, 50);
    lv_obj_set_height(ui_cmdG, 25);
    lv_obj_set_x(ui_cmdG, -50);
    lv_obj_set_y(ui_cmdG, 50);
    lv_obj_set_align(ui_cmdG, LV_ALIGN_CENTER);


    ui_LastWateringG = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LastWateringG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastWateringG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastWateringG, 0);
    lv_obj_set_y(ui_LastWateringG, -120);
    lv_obj_set_align(ui_LastWateringG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastWateringG, "");

    ui_LastRain = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_LastRain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LastRain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LastRain, 0);
    lv_obj_set_y(ui_LastRain, -90);
    lv_obj_set_align(ui_LastRain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LastRain, "");

    ui_RainFall = lv_label_create(ui_Garden);
    lv_obj_set_width(ui_RainFall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainFall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainFall, 1);
    lv_obj_set_y(ui_RainFall, -60);
    lv_obj_set_align(ui_RainFall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RainFall, "");

    ui_section = lv_dropdown_create(ui_Garden);
    lv_dropdown_set_options(ui_section, "Sekcja 1\nSekcja 2\nSekcja 3\nSekcja 4");
    lv_obj_set_width(ui_section, 100);
    lv_obj_set_height(ui_section, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_section, -150);
    lv_obj_set_y(ui_section, 90);
    lv_obj_set_align(ui_section, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_section, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_timeGarden = lv_dropdown_create(ui_Garden);
    lv_dropdown_set_options(ui_timeGarden, "15 min\n20 min\n25 min\n30 min\n40 min\n60min\n50 min\n60 min");
    lv_obj_set_width(ui_timeGarden, 100);
    lv_obj_set_height(ui_timeGarden, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeGarden, 150);
    lv_obj_set_y(ui_timeGarden, 90);
    lv_obj_set_align(ui_timeGarden, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeGarden, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GardenAut, ui_event_GardenAut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cmdG, ui_event_cmdG, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_section, ui_event_section, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeGarden, ui_event_timeGarden, LV_EVENT_ALL, NULL);

}
