// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"
uint8_t cmdToFunc = 0;
void checkCmdsGUI(uint8_t cmd)
{
    cmdToFunc = cmd;
}
