// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test
#define TENT_WATER_CMD 1
#define TENT_AUT_CMD 2
#define GARDEN_WATER_CMD 3
#define GARDEN_AUT_CMD 4
#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
extern uint8_t cmdToFunc;

#ifdef __cplusplus
extern "C" {
#endif
void checkCmdsGUI(uint8_t cmd);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
