// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t * ui_MainMenu;
void ui_event_GardenB(lv_event_t * e);
lv_obj_t * ui_GardenB;
void ui_event_TentB(lv_event_t * e);
lv_obj_t * ui_TentB;
lv_obj_t * ui_GLabel;
lv_obj_t * ui_TLabel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_TLabel;
lv_obj_t * ui_PLabel;
lv_obj_t * ui_LLabel;
lv_obj_t * ui_HLabel;
lv_obj_t * ui_TempOut;
lv_obj_t * ui_RHOut;
lv_obj_t * ui_Lux;
lv_obj_t * ui_Preasure;
lv_obj_t * ui_Time;
lv_obj_t * ui_Date;
// CUSTOM VARIABLES
lv_obj_t * uic_TempOut;


// SCREEN: ui_Garden
void ui_Garden_screen_init(void);
lv_obj_t * ui_Garden;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_LLastWateringG;
lv_obj_t * ui_LRainFall;
lv_obj_t * ui_LLastRain;
lv_obj_t * ui_LGardenAut;
lv_obj_t * ui_Label8;
void ui_event_GardenAut(lv_event_t * e);
lv_obj_t * ui_GardenAut;
lv_obj_t * ui_LcmdG;
void ui_event_cmdG(lv_event_t * e);
lv_obj_t * ui_cmdG;
lv_obj_t * ui_LastWateringG;
lv_obj_t * ui_LastRain;
lv_obj_t * ui_RainFall;
// CUSTOM VARIABLES


// SCREEN: ui_Tent
void ui_Tent_screen_init(void);
lv_obj_t * ui_Tent;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_LTempIn;
lv_obj_t * ui_Label10;
lv_obj_t * ui_LSoilMois;
lv_obj_t * ui_LWaterLvl;
lv_obj_t * ui_LRHIn;
lv_obj_t * ui_LTentAut;
void ui_event_TentAut(lv_event_t * e);
lv_obj_t * ui_TentAut;
lv_obj_t * ui_SoilMois;
lv_obj_t * ui_WaterLvl;
lv_obj_t * ui_RHIn;
lv_obj_t * ui_TempIn;
lv_obj_t * ui_LLastWateringT;
lv_obj_t * ui_LastWateringT;
lv_obj_t * ui_LcmdT;
void ui_event_cmdT(lv_event_t * e);
lv_obj_t * ui_cmdT;
lv_obj_t * ui_SoilMoisBar;
lv_obj_t * ui_WaterLvlBar;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_GardenB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Garden, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Garden_screen_init);
    }
}

void ui_event_TentB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Tent, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Tent_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_GardenAut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_GardenAut, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_cmdG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_cmdG, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_TentAut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_TentAut, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_cmdT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        checkCmds(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainMenu_screen_init();
    ui_Garden_screen_init();
    ui_Tent_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainMenu);
}
