// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
extern lv_obj_t * ui_MainMenu;
void ui_event_GardenB(lv_event_t * e);
extern lv_obj_t * ui_GardenB;
void ui_event_TentB(lv_event_t * e);
extern lv_obj_t * ui_TentB;
extern lv_obj_t * ui_GLabel;
extern lv_obj_t * ui_TLabel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TLabel;
extern lv_obj_t * ui_PLabel;
extern lv_obj_t * ui_LLabel;
extern lv_obj_t * ui_HLabel;
extern lv_obj_t * ui_TempOut;
extern lv_obj_t * ui_RHOut;
extern lv_obj_t * ui_Lux;
extern lv_obj_t * ui_Preasure;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Date;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TempOut;

// SCREEN: ui_Garden
void ui_Garden_screen_init(void);
extern lv_obj_t * ui_Garden;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_LLastWateringG;
extern lv_obj_t * ui_LRainFall;
extern lv_obj_t * ui_LLastRain;
extern lv_obj_t * ui_LGardenAut;
extern lv_obj_t * ui_Label8;
void ui_event_GardenAut(lv_event_t * e);
extern lv_obj_t * ui_GardenAut;
extern lv_obj_t * ui_LcmdG;
void ui_event_cmdG(lv_event_t * e);
extern lv_obj_t * ui_cmdG;
extern lv_obj_t * ui_LastWateringG;
extern lv_obj_t * ui_LastRain;
extern lv_obj_t * ui_RainFall;
// CUSTOM VARIABLES

// SCREEN: ui_Tent
void ui_Tent_screen_init(void);
extern lv_obj_t * ui_Tent;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_LTempIn;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_LSoilMois;
extern lv_obj_t * ui_LWaterLvl;
extern lv_obj_t * ui_LRHIn;
extern lv_obj_t * ui_LTentAut;
void ui_event_TentAut(lv_event_t * e);
extern lv_obj_t * ui_TentAut;
extern lv_obj_t * ui_SoilMois;
extern lv_obj_t * ui_WaterLvl;
extern lv_obj_t * ui_RHIn;
extern lv_obj_t * ui_TempIn;
extern lv_obj_t * ui_LLastWateringT;
extern lv_obj_t * ui_LastWateringT;
extern lv_obj_t * ui_LcmdT;
void ui_event_cmdT(lv_event_t * e);
extern lv_obj_t * ui_cmdT;
extern lv_obj_t * ui_SoilMoisBar;
extern lv_obj_t * ui_WaterLvlBar;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
